src/org/csu/mypetstore/domain/Cart.java
package org.csu.mypetstore.domain;

//import com.ibatis.common.util.PaginatedArrayList;
import org.csu.mypetstore.persistence.CartDAO;
import org.csu.mypetstore.persistence.Impl.CartDAOImpl;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class Cart implements Serializable {

  private CartDAO cartDAO;
  public Cart(){
    cartDAO = new CartDAOImpl();
  }
  private static final long serialVersionUID = 8329559983943337176L;
  private final Map<String, CartItem> itemMap = Collections.synchronizedMap(new HashMap<String, CartItem>());
  private  List<CartItem> itemList = new ArrayList<CartItem>();

  public Iterator<CartItem> getCartItems() {
    return itemList.iterator();
  }

  public List<CartItem> getCartItemList() {
    return itemList;
  }

  public int getNumberOfItems() {
    return itemList.size();
  }

  public Iterator<CartItem> getAllCartItems() {
    return itemList.iterator();
  }

  public boolean containsItemId(String itemId) {
    return itemMap.containsKey(itemId);
  }

  public void addItem(Item item, boolean isInStock, String userid) {
    CartItem cartItem = (CartItem) itemMap.get(item.getItemId());
    if (cartItem == null) {
      cartItem = new CartItem();
      cartItem.setItem(item);
      cartItem.setQuantity(0);
      cartItem.setInStock(isInStock);
      itemMap.put(item.getItemId(), cartItem);
      itemList.add(cartItem);
      if(userid != null && !userid.equals("")){
        //数据库中插入
        cartDAO.insertCartItem(cartItem, userid);
      }
    }
    cartItem.incrementQuantity();
    cartDAO.incrementQuantity(cartItem);
  }

  public Item removeItemById(String itemId) {
    CartItem cartItem = (CartItem) itemMap.remove(itemId);
    if (cartItem == null) {
      return null;
    } else {
      itemList.remove(cartItem);
      cartDAO.removeItemById(cartItem);
      return cartItem.getItem();
    }
  }

  public void incrementQuantityByItemId(String itemId) {
    CartItem cartItem = (CartItem) itemMap.get(itemId);
    cartItem.incrementQuantity();
    cartDAO.incrementQuantity(cartItem);
  }

  public void setQuantityByItemId(String itemId, int quantity) {
    CartItem cartItem = (CartItem) itemMap.get(itemId);
    cartItem.setQuantity(quantity);
//    cartDAO.incrementQuantity(cartItem);
    cartDAO.updateQuantityByItemId(cartItem, quantity);
  }

  public BigDecimal getSubTotal() {
    BigDecimal subTotal = new BigDecimal("0");
    Iterator<CartItem> items = getAllCartItems();
    while (items.hasNext()) {
      CartItem cartItem = (CartItem) items.next();
      Item item = cartItem.getItem();
      BigDecimal listPrice = item.getListPrice();
      BigDecimal quantity = new BigDecimal(String.valueOf(cartItem.getQuantity()));
      subTotal = subTotal.add(listPrice.multiply(quantity));
    }
    return subTotal;
  }

  public void clear(Cart cart,String workingItemId) {
    workingItemId = null;
    itemList.clear();
    itemMap.clear();
  }

  public List<CartItem> getCartItemListByUserid(String userid){
    return cartDAO.getCartItemListByUserid(userid);
  }

  public void addItem1(CartItem cartItem){
    itemMap.put(cartItem.getItem().getItemId(), cartItem);
    itemList.add(cartItem);
  }

  public void removeAllCartItemsByUserid(String userid){
    cartDAO.removeAllCartItemsByUserid(userid);
  }

  public void addItemQuantity(Item item, boolean isInStock,int quantity) {
    CartItem cartItem = (CartItem) itemMap.get(item.getItemId());
    if (cartItem == null) {
      cartItem = new CartItem();
      cartItem.setItem(item);
      cartItem.setQuantity(quantity);
      cartItem.setInStock(isInStock);
      itemMap.put(item.getItemId(), cartItem);
      itemList.add(cartItem);
    }
    else {
      //cartItem.incrementQuantity();
      cartItem.setQuantity(quantity);
    }
  }
}

web/WEB-INF/jsp/cart/Cart.jsp
<%@ include file="../common/IncludeTop.jsp"%>
<div>
	<script type="text/javascript">
		$(document).ready(function(){
			$("#Catalog").hide().fadeIn();
		});
	</script>
</div>

<div id="BackLink">
	<a href="main">Return to Main Menu</a>
</div>

<div id="Catalog">

<div id="Cart">

<h2>Shopping Cart</h2>
	<form action="updateCartQuantities?cart=${sessionScope.cart}" method="post">
		<table>
			<tr>
				<th><b>Item ID</b></th>
				<th><b>Product ID</b></th>
				<th><b>Description</b></th>
				<th><b>In Stock?</b></th>
				<th><b>Quantity</b></th>
				<th><b>List Price</b></th>
				<th><b>Total Cost</b></th>
				<th>&nbsp;</th>
			</tr>

			<c:if test="${sessionScope.cart.numberOfItems == 0}">
				<tr>
					<td colspan="8"><b>Your cart is empty.</b></td>
				</tr>
			</c:if>

			<c:forEach var="cartItem" items="${sessionScope.cart.cartItems}">
				<tr class="cartItem" id="${cartItem.item.itemId}">
					<td>
						<a href="viewItem?cartItemId=${cartItem.item.itemId}">${cartItem.item.itemId}</a>
					</td>
					<td>${cartItem.item.product.productId}</td>
					<td>${cartItem.item.attribute1} ${cartItem.item.attribute2}
							${cartItem.item.attribute3} ${cartItem.item.attribute4}
							${cartItem.item.attribute5} ${cartItem.item.product.name}</td>
					<td>${cartItem.inStock}</td>
					<td>
						<input id="quantity" type="text" name="${cartItem.item.itemId}" value="${cartItem.quantity}"/>
					</td>
					<td>
						<fmt:formatNumber value="${cartItem.item.listPrice}" pattern="$#,##0.00" /></td>

					<td id="${cartItem.item.itemId}" class="td"><fmt:formatNumber value="${cartItem.total}" pattern="$#,##0.00" /></td>
					<td>
						<a href="removeItemFromCart?workingItemId=${cartItem.item.itemId}" class="Button">Remove</a>
					</td>
				</tr>
			</c:forEach>
			<tr>
				<td colspan="7">
					Sub Total:
					<span id="subtotal"><fmt:formatNumber value="${sessionScope.cart.subTotal}" pattern="$#,##0.00" /></span>

					<input type="submit" value="Update Cart" name="updateCartQuantities" />
				</td>
				<td>&nbsp;</td>
			</tr>
		</table>
	</form>
		<c:if test="${sessionScope.cart.numberOfItems > 0}">
			<a href="newOrderForm" class="Button" id="button1">Proceed to Checkout</a>
		</c:if>
</div>

<div id="MyList">
  <c:if test="${sessionScope.account != null}">
	<c:if test="${!sessionScope.authenticated}">
	  <c:if test="${!empty sessionScope.account.listOption}">
	    <%@ include file="IncludeMyList.jsp"%>
      </c:if>
	</c:if>
  </c:if>
</div>

<div id="Separator">&nbsp;</div>
</div>

<script type="text/javascript" src="js/Cart.js"></script>

<%@ include file="../common/IncludeBottom.jsp"%>

web/WEB-INF/jsp/cart/Checkout.jsp
<%@ include file="../common/IncludeTop.jsp"%>
<div>
	<script type="text/javascript">
		$(document).ready(function(){
			$("#Catalog").hide().fadeIn();
		});
	</script>
</div>
<div id="BackLink">
	<a href="viewCart">Return to Shopping Cart</a>
</div>

<div id="Catalog">

<table>
	<tr>
		<td>
		<h2>Checkout Summary</h2>

		<table>

			<tr>
				<td><b>Item ID</b></td>
				<td><b>Product ID</b></td>
				<td><b>Description</b></td>
				<td><b>In Stock?</b></td>
				<td><b>Quantity</b></td>
				<td><b>List Price</b></td>
				<td><b>Total Cost</b></td>
			</tr>

			<c:forEach var="cartItem" items="${sessionScope.cart.cartItems}">
				<tr>
					<td>
						<a href="viewItem?cartItemId=${cartItem.item.itemId}">${cartItem.item.itemId}</a>
					</td>
					<td>${cartItem.item.product.productId}</td>
					<td>${cartItem.item.attribute1} ${cartItem.item.attribute2}
					${cartItem.item.attribute3} ${cartItem.item.attribute4}
					${cartItem.item.attribute5} ${cartItem.item.product.name}</td>
					<td>${cartItem.inStock}</td>
					<td>${cartItem.quantity}</td>
					<td><fmt:formatNumber value="${cartItem.item.listPrice}"
						pattern="$#,##0.00" /></td>
					<td><fmt:formatNumber value="${cartItem.total}"
						pattern="$#,##0.00" /></td>
				</tr>
			</c:forEach>
			<tr>
				<td colspan="7">Sub Total: <fmt:formatNumber
					value="${sessionScope.cart.subTotal}" pattern="$#,##0.00" /></td>
			</tr>
		</table>

		<td>&nbsp;</td>

	</tr>
</table>

</div>

<%@ include file="../common/IncludeBottom.jsp"%>

web/WEB-INF/jsp/cart/IncludeMyList.jsp
<c:if test="${!empty sessionScope.myList}">
	<div>
		<script type="text/javascript">
			$(document).ready(function(){
				$("#Catalog").hide().fadeIn();
			});
		</script>
	</div>
	<p>Pet Favorites <br />
	Shop for more of your favorite pets here.</p>
	<ul>
		<c:forEach var="product" items="${sessionScope.myList}">
			<li>
				<a href="viewProduct?productId=${product.productId}">${product.name}</a>(${product.productId})
			</li>
		</c:forEach>
	</ul>

</c:if>